### ISSUE TITLE
`os.mkdir(repo_root)` Not creating .autoversion directory

### ISSUE THREAD

**Issue by pastram-i** [timkpaine/jupyterlab_autoversion#152]
**Describe the bug**
[`os.mkdir(repo_root)`](https://github.com/timkpaine/jupyterlab_autoversion/blob/main/jupyterlab_autoversion/storage/git/__init__.py#L18) isn't created on initialization. 

Jupyter logs:
```
> kubectl logs -n xyz jupyter-dduke --follow | grep autoversion
[I 2024-09-06 17:37:39.967 ServerApp] jupyterlab_autoversion | extension was successfully linked.
Installing jupyterlab_autoversion handler on path /user/dduke/autoversion
[I 2024-09-06 17:37:40.923 ServerApp] jupyterlab_autoversion | extension was successfully loaded.
```
Directory:
```
root@jupyter-dduke:/# ls -al /usr/local/lib/python3.11/site-packages/jupyterlab_autoversion/storage/git
total 16
drwsrwsr-x 1 root users   93 Aug 21 22:07 .
drwsrwsr-x 1 root users   76 Aug 21 22:07 ..
-rw-rw-r-- 1 root users 1388 Aug 21 22:07 __init__.py
drwsrwsr-x 1 root users  126 Aug 21 22:07 __pycache__
-rw-rw-r-- 1 root users 2221 Aug 21 22:07 diff.py
-rw-rw-r-- 1 root users 2429 Aug 21 22:07 handlers.py
-rw-rw-r-- 1 root users  969 Aug 21 22:07 hook.py
```
**Expected behavior**
Directory is created, and extension works as expected.

**Screenshots**
This results in some oddities, like Diff not rendering correctly (due to no `.autoversion/diff` directory) and versions not persisting through pod restarts.
![image](https://github.com/user-attachments/assets/f6935756-a71c-4517-b681-5ef9a0b5d8f1)

**Environment:**
I have a pretty unique setup with Z2JH (kube) spinning up user pods on AWS EKS. I run quite a bit of customization on user private/shared directories (AWS EFS filesystems), but this shouldn't effect the directory being created for the extension as permissions in that directory appear to be 665.

**Comment by pastram-i** [comment]
I did a `find` with the identifier of one of the past versions (`7d664e`).
`sudo find / -type f -exec grep -Hn "7d664e" {} \;`

It looks like `.autoversion` may have actually been made, but in the incorrect directory?
```
/usr/local/lib/python3.11/site-packages/jupyterlab_commenting_service/.autoversion/.git/refs/tags/a81a7c7f2daac9d218a445670215ad367883c4202789d5ddd67f6b497952aea1-2:1:7d664e37c6dcf3b9cc47ef7252d4225c8a583281
./usr/local/lib/python3.11/site-packages/jupyterlab_commenting_service/.autoversion/.git/logs/refs/heads/master:3:d5c1a6421f51538b74dfd26d8770e61f6040a093 7d664e37c6dcf3b9cc47ef7252d4225c8a583281 dduke <dduke@jupyter-dduke> 1725644275 +0000        a81a7c7f2daac9d218a445670215ad367883c4202789d5ddd67f6b497952aea1-2
./usr/local/lib/python3.11/site-packages/jupyterlab_commenting_service/.autoversion/.git/logs/refs/heads/master:4:7d664e37c6dcf3b9cc47ef7252d4225c8a583281 8c0ad60efe138aa5a18c30fb9d2cf55e2940ba86 dduke <dduke@jupyter-dduke> 1725644447 +0000        a81a7c7f2daac9d218a445670215ad367883c4202789d5ddd67f6b497952aea1-3
./usr/local/lib/python3.11/site-packages/jupyterlab_commenting_service/.autoversion/.git/logs/HEAD:3:d5c1a6421f51538b74dfd26d8770e61f6040a093 7d664e37c6dcf3b9cc47ef7252d4225c8a583281 dduke <dduke@jupyter-dduke> 1725644275 +0000 a81a7c7f2daac9d218a445670215ad367883c4202789d5ddd67f6b497952aea1-2
./usr/local/lib/python3.11/site-packages/jupyterlab_commenting_service/.autoversion/.git/logs/HEAD:4:7d664e37c6dcf3b9cc47ef7252d4225c8a583281 8c0ad60efe138aa5a18c30fb9d2cf55e2940ba86 dduke <dduke@jupyter-dduke> 1725644447 +0000 a81a7c7f2daac9d218a445670215ad367883c4202789d5ddd67f6b497952aea1-3
```

**Comment by pastram-i** [comment]
Possibly stepping closer here..

Turns out the creation of `.autoversion` in the `./jupyterlab_commenting_service` was a symptom of a bug with the commenting service package itself. This changed my `$PWD`. Once jupyter was 'started here', it's where it created the `.autoversion` directory. I've since removed the commenting service to address this later.

Because of how directories are handled with this Z2JH environment (see environment notes on first commend), I've manually created an `autoversion` directory on my AWS EFS.

I've created the directory and repo the same as is done in [__init__.py](https://github.com/timkpaine/jupyterlab_autoversion/blob/main/jupyterlab_autoversion/storage/git/__init__.py) at this location by 'manually' running the below.
```python
import os
import os.path
from git import Repo
repo_root = os.path.join(os.path.abspath(os.curdir), ".autoversion")
os.mkdir(repo_root)
repo = Repo.init(repo_root)

ignore_root = os.path.join(os.path.abspath(os.curdir), ".gitignore")
with open(ignore_root, "w") as fp:
    fp.write("\n.autoversion\n")
```

Jupyter/autoversion extension by start as expected now. However, anytime a file is saved there is an 'uncaught error'.
When I'm parsing the logs, I see the below:
```python
2024-09-09 21:54:43,339 - ServerApp - ERROR - Uncaught exception PUT /user/dduke/api/contents/Private/Untitled2.ipynb?1725918883180 (::ffff:172.14.105.26)
HTTPServerRequest(protocol='http', host='jupyter-dev.directions.tools', method='PUT', uri='/user/dduke/api/contents/Private/Untitled2.ipynb?1725918883180', version='HTTP/1.1', remote_ip='::ffff:172.14.105.26')
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/git/objects/commit.py", line 695, in create_from_tree
    repo.head.set_commit(new_commit, logmsg=message)
  File "/usr/local/lib/python3.11/site-packages/git/refs/symbolic.py", line 341, in set_commit
    self.set_object(commit, logmsg)
  File "/usr/local/lib/python3.11/site-packages/git/refs/symbolic.py", line 388, in set_object
    return self._get_reference().set_object(object, logmsg)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/git/refs/reference.py", line 93, in set_object
    oldbinsha = self.commit.binsha
                ^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/git/refs/symbolic.py", line 297, in _get_commit
    obj = self._get_object()
          ^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/git/refs/symbolic.py", line 288, in _get_object
    return Object.new_from_sha(self.repo, hex_to_bin(self.dereference_recursive(self.repo, self.path)))
                                                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/git/refs/symbolic.py", line 168, in dereference_recursive
    hexsha, ref_path = cls._get_ref_info(repo, ref_path)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/git/refs/symbolic.py", line 278, in _get_ref_info
    return cls._get_ref_info_helper(repo, ref_path)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/git/refs/symbolic.py", line 257, in _get_ref_info_helper
    raise ValueError("Reference at %r does not exist" % ref_path)
ValueError: Reference at 'refs/heads/master' does not exist
```

**Comment by pastram-i** [comment]
I'm thinking this has to do with an older version of Git.

Because I'm using Debian Bullseye, it looks like the newest version of git I can get it `2.30.2`. Here is the Dockerfile for that
```Dockerfile
FROM --platform=linux/arm64/v8 python:3.11-bullseye

RUN apt update \
    && apt upgrade -y \
    && apt install -y --no-install-recommends \
        ca-certificates \
        dnsutils \
        iputils-ping \
        tini \
        git \
        curl \
        gcc \
        python3-dev \
        sudo \
        jq \
        dirmngr \
        software-properties-common \
        cron \
        unzip \
        ripgrep \
        sqlite3 \
        nano \
    && rm -rf /var/lib/apt/lists/*

RUN pip install -U pip
RUN pip install \
        jupyterhub==4.0.2 \
        jupyterlab>=4.0.8 \
        notebook>=7.0.6 \
        nbclassic~=1.0.0 \
        nbgitpuller~=1.2.0 \
        ipykernel~=6.26.0 \
        poetry~=1.6.1 \
        jupyterlab-autoversion

ENV DEBIAN_FRONTEND=noninteractive \
    RPY2_CFFI_MODE=ABI \
# User Variables
    NB_USER=jovyan \
    NB_UID=1000 \
    NB_GID=100 \
    HOME=/home/jovyan \
    LANG=en_US.UTF-8 \
    LANGUAGE=en_US.UTF-8 \
    SHELL=/bin/bash \
    USR_BIN=/usr/local/bin \
# Jupyter Variablse
    JUPYTER_PORT=8888 \
    JUPYTER_DIR=$JUPYTER_DIR \
# Python/Pip Variables
    PYTHONUNBUFFERED=1 \
# Poetry Variables
    POETRY_VIRTUALENVS_IN_PROJECT=1 \
    POETRY_NO_INTERACTION=1 \
    POETRY_VIRTUALENVS_CREATE=1
ENV PATH="$USR_BIN:$PATH"
RUN adduser \
        --disabled-password \
        --gecos "Default user" \
        --uid ${NB_UID} \
        --home ${HOME} \
        --force-badname \
        ${NB_USER}

RUN curl -LJO https://raw.githubusercontent.com/jupyter/docker-stacks/d400e383cc1df74dde5bea5468f8bb812546d62d/images/docker-stacks-foundation/fix-permissions \
    -LJO https://raw.githubusercontent.com/jupyter/docker-stacks/d400e383cc1df74dde5bea5468f8bb812546d62d/images/base-notebook/start-notebook.sh \
    -LJO https://raw.githubusercontent.com/jupyter/docker-stacks/d400e383cc1df74dde5bea5468f8bb812546d62d/images/base-notebook/start-singleuser.sh \
    -LJO https://raw.githubusercontent.com/jupyter/docker-stacks/d400e383cc1df74dde5bea5468f8bb812546d62d/images/docker-stacks-foundation/start.sh \
    -LJO https://raw.githubusercontent.com/jupyter/docker-stacks/d400e383cc1df74dde5bea5468f8bb812546d62d/images/base-notebook/docker_healthcheck.py
RUN mv fix-permissions \
    start-notebook.sh \
    start-singleuser.sh \
    start.sh \
    ${USR_BIN}/
RUN chmod -R 777 \
    ${USR_BIN}/

RUN fix-permissions /home/${NB_USER}
RUN fix-permissions /usr/local/lib/python3.11/site-packages

EXPOSE $JUPYTER_PORT
ENTRYPOINT ["tini", "-g", "--"]
USER ${NB_USER}
ENV PATH="$USR_BIN:$PATH"
WORKDIR /home/jovyan
CMD ["/bin/bash", "-c", "start-notebook.sh"]
```

This shows `.autoversion` in the correct `/home/jovyan` directory, but with no `/refs/heads/master` directory.

But if I use the base `minimal-notebook` (which uses Ubuntu 24.04; Debian Trixie), my git version is `2.43.0`, but everything works as expected.
```Dockerfile
FROM --platform=linux/arm64/v8 quay.io/jupyter/minimal-notebook:python-3.11 

RUN pip install jupyterlab-autoversion
```

I'm unsure how to address this currently. I do have other requirements elsewhere that (for now) don't allow us to upgrade to Bookworm (while there's no python images that supports Trixie yet), and it would be quite a re-write to migrate to a ubuntu or debian image instead of python.
